server:
  port: 5001

#TODO: Ideally credentials should be kept in secrets
spring:
  application:
    name: bite-speed-assignment
  datasource:
    username: identity_recon_db_user
    password: QOiHuRAFQ9KEjKMFUIMuhssmJtwmwiLC
    url: jdbc:postgresql://dpg-cpiprn4f7o1s73bkrsgg-a.ohio-postgres.render.com:5432/identity_recon_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
